### ISSUE TITLE
ERROR: for sonos  "host" network_mode is incompatible with port_bindings

### ISSUE THREAD

**Issue by leylon** [maxandersen/internet-monitoring#9]
![image](https://user-images.githubusercontent.com/5273188/124489856-0fbfb200-dd77-11eb-82fd-ece2830c5a16.png)

**Comment by JeanOsorio** [comment]
open the docker-compose.yaml file and delete the line with the network_mode> host

**Comment by VRevol** [comment]
When running on a synology docker and you want to discover sonos on your local network outside of synology, I found that one can use: "network_mode: host" in combination with "expose" and do not use the port binding.

```
  sonos:
    tty: true
    stdin_open: true
    image: maxandersen/sonos_exporter
    container_name: sonosexp
    command:
      - '--address=0.0.0.0:1915'
    expose:
      - "1915"
#    ports:
#      - "1915:1915"
    restart: unless-stopped
    network_mode: host
```
